### PR TITLE
docs(irm): speed is not constant

### PR DESCRIPTION
**Pull request by Rubilmax**
- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/0b0fd532-796b-4663-b3f5-03c0c8caa701

### CODE REVIEW

**Review by MerlinEgalite — APPROVED** [review]

**Review by Jean-Grimal — APPROVED** [review]

**Review by MerlinEgalite — APPROVED** [review]

**Comment by MerlinEgalite** [comment]
conflicts :/

**Review by MathisGD — COMMENTED** [review]
I don't get what was wrong, except maybe the "slightly"

**Comment by Rubilmax** [comment]
> I don't get what was wrong, except maybe the "slightly"

For example, as explained in the associated issue, when utilization is at 89% the speed starts to decrease and then when it goes above 90% starts to increase again

**Comment by MathisGD** [comment]
so the rate is underestimated, as stated in the comment no ?

**Review by MathisGD — APPROVED** [review]

**Review by MerlinEgalite — APPROVED** [review]

**Pull request merged**
